version: "3.9"
services:
  database:
    image: mysql:8
    ports:
    - "3306:3306"
    restart: unless-stopped
    env_file: .env
    volumes:
      - dbdata:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
 

  wordpress:
    build: .
    ports:
      - "6060:80"
    restart: always
    volumes:
      - ./wp-content/:/var/www/app/wordpress/wp-content
    env_file: .env
    environment:
      - SLEEP_TIME=18
    depends_on:
      - database


  loadbalancer:
    image: nginx:latest
    ports:
    - "80:80"
    volumes:
    - ./nginx/:/etc/nginx/conf.d/
    depends_on:
      - wordpress

volumes:
  dbdata:
